---
title: "Cars - CO2 Emissions and Effciency"
description: |
  This project's goal is to help you make the most eco-friendly decision when buying a new car!
author:
  - name: Akhilesh Sangaraju 
date: "`r Sys.Date()`"
site: distill::distill_website
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rvest)
library(ggthemes)
library(janitor)
library(dplyr)
library(plotly)
```

```{r}
dataset <- read_csv(file="CO2Emissions.csv")
dataset <- clean_names(dataset)
```

```{r}
dataset |>
  select(make, model, co2_emissions_g_km) |>
  group_by(make) |>
  mutate(num_models = n(), sum_emissions = sum(co2_emissions_g_km)) |>
  summarize (make, average_emissions = sum_emissions / num_models) |>
  ungroup() |>
  unique() |>
  ggplot(mapping = aes(x = make, y = average_emissions)) +
  geom_col(fill="dodgerblue") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 8)) +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.2)) +
  theme(axis.title.x = element_text(margin = margin(t = 5, r = 0, b = 0, l = 0))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  labs(title = "Average Tailpipe Emissions of CO2 by Car Brand",
       subtitle= "Of the gas powered cars sold in the US, Honda's have the lowest average CO2 emissions",
       x = "Brand",
       y = "Average CO2 Emissions (G/km)",
       caption = "Source: CO2 Emission by Vehicles") +
  theme(plot.subtitle = element_text(size = 10)) +
  theme(plot.title = element_text(face = "bold"))
```

[@Emission]

```{r}
dataset2 <- read.csv(file="ElectricCarData_Clean.csv")
```

```{r}
EVdata <- dataset2 |>
          select(Brand, Model, Range_Km, Efficiency_WhKm) |>
          arrange(Brand) |>
          ggplot(mapping = aes(x = Range_Km, y = Efficiency_WhKm, color = Brand, label = Model)) +
          geom_point() +
          theme_minimal() +
          labs(title="Range and Efficiency of Different Electric Vehicles",
               x = "Range (Km)",
               y = "Effciency (Wh/KM - Lower is better)")
ggplotly(EVdata)
```

[@EV]
